node {
   
        echo "STAGE: Checkout Source >>> STARTS";

        stage('Git Checkout'){
            checkout scm
        }
        echo "STAGE: Checkout Source >>> ENDS";
            
        echo "STAGE: Run Jmeter test >>> STARTS";
        
        stage ('Run JMeter Test'){
        bat 'D:/apache-jmeter-5.2.1/bin/jmeter.bat -n -t D:/Training/petstore-demo.jmx -l D:/Training/petstore-jtl-jenkins.jtl'
        }
            echo "STAGE: Run Jmeter test >>> ENDS";
     }
