node {
   
        echo "STAGE: Checkout Source >>> STARTS";

        stage('Git Checkout'){
            checkout scm
        }
        echo "STAGE: Checkout Source >>> ENDS";
            
        echo "STAGE: Run Jmeter test >>> STARTS";
        
        stage ('Run JMeter Test'){
        bat 'C:/Users/ladda/Desktop/Desktop/Training_Data/Jmeter/apache-jmeter-5.5/bin/jmeter.bat -n -t C:/Users/ladda/Desktop/Desktop/Training_Data/Jmeter/apache-jmeter-5.5/bin/Jmeter_Jenkins_Run.jmx -l C:/Users/ladda/Desktop/Desktop/Training_Data/Jmeter/apache-jmeter-5.5/bin/Jenkins_Jmeter_File_27thJune.jtl'
        }
            echo "STAGE: Run Jmeter test >>> ENDS";
     }
